[workspace]
resolver = "3"
members = [
    "benchmark",
    "quest01",
]

[workspace.metadata.quest01]
start_time = 2025-08-27T00:41:40.438043
completion_time = 2025-08-27T01:20:15.028981

[profile.release]
debug = true
